version: '3'
services:
  edge-admin:
    image: goedge/edge-admin:latest
    container_name: edge-admin
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "7788:7788"
      - "8001:8001"
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./configs:/usr/local/goedge/edge-admin/configs
      - ./logs:/usr/local/goedge/edge-admin/logs
      - ./edge-api-configs:/usr/local/goedge/edge-admin/edge-api/configs
      - ./edge-api-logs:/usr/local/goedge/edge-admin/edge-api/logs
